"""
Setting version
"""
_COMMENT = """#
#  This file was autogenerated from a template  DO NOT EDIT!!
#  Changes should be made to the original file (pyproject_setting.toml)
#
"""

if __name__ == '__main__':
    import sys
    import toml
    from os.path import exists

    # get tags from parse as version
    if len(sys.argv) < 2:
        sys.exit(1)
    ref = sys.argv[1]
    version = ref.removeprefix('refs/tags/')

    # generate pyproject.toml
    with open("pyproject_setting.toml", "r", encoding='utf-8') as f:
        parsed_toml = toml.loads(f.read())
    parsed_toml['project']['version'] = version
    with open("pyproject.toml", "w", encoding='utf-8') as f:
        toml.dump(parsed_toml, f)
    with open('pyproject.toml', 'r+', encoding='utf-8') as f:
        file_content = f.read()
        f.seek(0, 0)
        f.write(_COMMENT + '\n' + file_content)

    # check change log
    filepath = f"./docs/changelogs/changelog_{version}.md"
    if not exists(filepath):
        open(filepath, 'x', encoding='utf-8').close()
    print(filepath)
